# Generated by Django 3.2.25 on 2024-12-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='polls.Category'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
